# This is a basic workflow to help you get started with Actions

name: Try Log Secrets

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Log the secret
        run: echo ${{ secrets.TOKEN_SECRET }}
