# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sentosa Assigment CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Wait on
        # You may pin to the exact commit or the version.
        # uses: iFaxity/wait-on-action@63d56fe931cdde4fc340587a28ad8d5c461e7d16
        uses: iFaxity/wait-on-action@v1
        with:
          resource: https://google.com
          delay: 60000
          verbose: true
          
      - name: NPM jest
        run: | 
          npm ci
          npm test
          wait-on: 'https://google.com'
          wait-on-timeout: 30000
